# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoint-hypermedia

# httptrace, trace, info, metrics, health

management:
  endpoints:
    web:
      exposure:
        include: "*"
      security:
        enabled: false
      health:
        sensitive: true
        show-details: "always"

server:
  servlet.context-path: "/rest-spring"

info:
  app:
    name: "restfull-spring"
    description: "Restfull Sample Spring application"
    version: "1.0.0"