insert into ALPHA.ALPHA_TABLE (ALPHA_ID, ALPHA_STRING) Values(1, 'A1_DEV');
insert into ALPHA.ALPHA_TABLE (ALPHA_ID, ALPHA_STRING) Values(2, 'A2_DEV');
insert into ALPHA.ALPHA_TABLE (ALPHA_ID, ALPHA_STRING) Values(3, 'A3_DEV');