insert into BETA.BETA_TABLE (BETA_ID, BETA_STRING) Values(1, 'B1_DEV');
insert into BETA.BETA_TABLE (BETA_ID, BETA_STRING) Values(2, 'B2_DEV');
insert into BETA.BETA_TABLE (BETA_ID, BETA_STRING) Values(3, 'B3_DEV');