version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: DB_Spring_6_REST_POC
    environment:
      MYSQL_DATABASE: db-spring6-rest
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - spring6_rest_db:/var/lib/mysql
# Names our volume
volumes:
  spring6_rest_db: